### ISSUE TITLE
Parse error: syntax error, unexpected '*'

### ISSUE THREAD

**Issue by benjaminleonard** [sjelfull/Craft-UptimeRobot#1]
Hey, thanks for the plugin!
I got this error:

`Parse error: syntax error, unexpected '*', expecting ',' or ';' in /var/www/craft/plugins/uptimerobot/controllers/UptimeRobotController.php on line 20`

Was fixed by replacing
`protected $_cacheDuration = 60 * 5; // Default to 5 minutes`
with
`protected $_cacheDuration = 300; // Default to 5 minutes`

I'm running Craft CMS 2.6.2987. It seems to work out of the box no problem on my local Craft installation, got the error on the server.

**Comment by sjelfull** [comment]
Thanks for reporting. This might be a difference between PHP versions, probably.

Could you send a pull request with the fix?

**Comment by benjaminleonard** [comment]
Done, hope that's all okay – haven't sent a pull request before.

Thanks!

**Comment by sjelfull** [comment]
Perfect!
